--
-- PostgreSQL database dump
--

-- Dumped from database version 13.0
-- Dumped by pg_dump version 13.0

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: cheap_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.cheap_payment (
    id integer NOT NULL,
    credit_card_number character varying NOT NULL,
    card_holder character varying NOT NULL,
    expiration_date timestamp without time zone NOT NULL,
    security_code character varying(32),
    amount double precision NOT NULL
);


ALTER TABLE public.cheap_payment OWNER TO postgres;

--
-- Name: cheap_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.cheap_payment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.cheap_payment_id_seq OWNER TO postgres;

--
-- Name: cheap_payment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.cheap_payment_id_seq OWNED BY public.cheap_payment.id;


--
-- Name: expensive_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.expensive_payment (
    id integer NOT NULL,
    credit_card_number character varying NOT NULL,
    card_holder character varying NOT NULL,
    expiration_date timestamp without time zone NOT NULL,
    security_code character varying(32),
    amount double precision NOT NULL
);


ALTER TABLE public.expensive_payment OWNER TO postgres;

--
-- Name: expensive_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.expensive_payment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.expensive_payment_id_seq OWNER TO postgres;

--
-- Name: expensive_payment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.expensive_payment_id_seq OWNED BY public.expensive_payment.id;


--
-- Name: premium_payment; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.premium_payment (
    id integer NOT NULL,
    credit_card_number character varying NOT NULL,
    card_holder character varying NOT NULL,
    expiration_date timestamp without time zone NOT NULL,
    security_code character varying(32),
    amount double precision NOT NULL
);


ALTER TABLE public.premium_payment OWNER TO postgres;

--
-- Name: premium_payment_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

CREATE SEQUENCE public.premium_payment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public.premium_payment_id_seq OWNER TO postgres;

--
-- Name: premium_payment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: postgres
--

ALTER SEQUENCE public.premium_payment_id_seq OWNED BY public.premium_payment.id;


--
-- Name: cheap_payment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cheap_payment ALTER COLUMN id SET DEFAULT nextval('public.cheap_payment_id_seq'::regclass);


--
-- Name: expensive_payment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expensive_payment ALTER COLUMN id SET DEFAULT nextval('public.expensive_payment_id_seq'::regclass);


--
-- Name: premium_payment id; Type: DEFAULT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.premium_payment ALTER COLUMN id SET DEFAULT nextval('public.premium_payment_id_seq'::regclass);


--
-- Data for Name: cheap_payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.cheap_payment (id, credit_card_number, card_holder, expiration_date, security_code, amount) FROM stdin;
\.


--
-- Data for Name: expensive_payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.expensive_payment (id, credit_card_number, card_holder, expiration_date, security_code, amount) FROM stdin;
\.


--
-- Data for Name: premium_payment; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.premium_payment (id, credit_card_number, card_holder, expiration_date, security_code, amount) FROM stdin;
1	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
2	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
3	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
4	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
5	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
6	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
7	3530111333300000	mostafa fouad	2200-01-21 18:12:33.747907	\N	1990
8	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
9	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
10	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
11	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
12	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
13	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
14	3530111333300000	Mostafa Fouad	2200-01-21 18:12:33.747907	424	1990
15	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
16	3530111333300000	Mostafa Fouad	2200-01-21 18:12:33.747907	424	1990
17	3530111333300000	Mostafa Fouad	2200-01-21 18:12:33.747907	424	1990
18	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
19	3530111333300000	Mostafa Fouad	2200-01-21 18:12:33.747907	424	1990
20	3530111333300000	mostafa_fouad	2200-01-21 18:12:33.747907	\N	1990
\.


--
-- Name: cheap_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.cheap_payment_id_seq', 1, false);


--
-- Name: expensive_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.expensive_payment_id_seq', 1, false);


--
-- Name: premium_payment_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.premium_payment_id_seq', 20, true);


--
-- Name: cheap_payment cheap_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.cheap_payment
    ADD CONSTRAINT cheap_payment_pkey PRIMARY KEY (id);


--
-- Name: expensive_payment expensive_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.expensive_payment
    ADD CONSTRAINT expensive_payment_pkey PRIMARY KEY (id);


--
-- Name: premium_payment premium_payment_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.premium_payment
    ADD CONSTRAINT premium_payment_pkey PRIMARY KEY (id);


--
-- PostgreSQL database dump complete
--

