"""empty message

Revision ID: 2579bda21c78
Revises: 
Create Date: 2021-01-21 18:34:31.268512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2579bda21c78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cheap_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_number', sa.String(), nullable=False),
    sa.Column('card_holder', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('security_code', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('expensive_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_number', sa.String(), nullable=False),
    sa.Column('card_holder', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('security_code', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('premium_payment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credit_card_number', sa.String(), nullable=False),
    sa.Column('card_holder', sa.String(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('security_code', sa.String(length=32), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('premium_payment')
    op.drop_table('expensive_payment')
    op.drop_table('cheap_payment')
    # ### end Alembic commands ###
